[package]
name = "spann-py"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "spann"
crate-type = ["cdylib"]

[dependencies]
half = "2.7.1"
ndarray = "0.17.1"
pyo3 = { version = "0.23.4", features = ["abi3-py310", "extension-module"] }
spann = { version = "0.2.0" }
